export const REQUERENTES = [
  { value: '1ª Delegacia de Polícia Civil Natal/RN', label: '1ª Delegacia de Polícia Civil Natal/RN' },
  { value: '2ª Delegacia de Polícia Civil Natal/RN', label: '2ª Delegacia de Polícia Civil Natal/RN' },
  { value: '3ª Delegacia de Polícia Civil Natal/RN', label: '3ª Delegacia de Polícia Civil Natal/RN' },
  { value: '4ª Delegacia de Polícia Civil Natal/RN', label: '4ª Delegacia de Polícia Civil Natal/RN' },
  { value: '5ª Delegacia de Polícia Civil Natal/RN', label: '5ª Delegacia de Polícia Civil Natal/RN' },
  { value: '6ª Delegacia de Polícia Civil Natal/RN', label: '6ª Delegacia de Polícia Civil Natal/RN' },
  { value: '7ª Delegacia de Polícia Civil Natal/RN', label: '7ª Delegacia de Polícia Civil Natal/RN' },
  { value: '8ª Delegacia de Polícia Civil Natal/RN', label: '8ª Delegacia de Polícia Civil Natal/RN' },
  { value: '9ª Delegacia de Polícia Civil Natal/RN', label: '9ª Delegacia de Polícia Civil Natal/RN' },
  { value: '10ª Delegacia de Polícia Civil Natal/RN', label: '10ª Delegacia de Polícia Civil Natal/RN' },
  { value: '11ª Delegacia de Polícia Civil Natal/RN', label: '11ª Delegacia de Polícia Civil Natal/RN' },
  { value: '12ª Delegacia de Polícia Civil Natal/RN', label: '12ª Delegacia de Polícia Civil Natal/RN' },
  { value: '13ª Delegacia de Polícia Civil Natal/RN', label: '13ª Delegacia de Polícia Civil Natal/RN' },
  { value: '14ª Delegacia de Polícia Civil Natal/RN', label: '14ª Delegacia de Polícia Civil Natal/RN' },
  { value: '15ª Delegacia de Polícia Civil Natal/RN', label: '15ª Delegacia de Polícia Civil Natal/RN' },
  { value: '16ª Delegacia de Polícia Civil Natal/RN', label: '16ª Delegacia de Polícia Civil Natal/RN' },
  { value: '17ª Delegacia de Polícia Civil Parnamirim/RN', label: '17ª Delegacia de Polícia Civil Parnamirim/RN' },
  { value: '18ª Delegacia de Polícia Civil Parnamirim/RN', label: '18ª Delegacia de Polícia Civil Parnamirim/RN' },
  { value: '19ª Delegacia de Polícia Civil Parnamirim/RN', label: '19ª Delegacia de Polícia Civil Parnamirim/RN' },
  { value: '20ª Delegacia de Polícia Civil Macaíba/RN', label: '20ª Delegacia de Polícia Civil Macaíba/RN' },
  { value: '21ª Delegacia de Polícia Civil São Gonçalo do Amarante/RN', label: '21ª Delegacia de Polícia Civil São Gonçalo do Amarante/RN' },
  { value: '22ª Delegacia de Polícia Civil Ceará Mirim/RN', label: '22ª Delegacia de Polícia Civil Ceará Mirim/RN' },
  { value: '23ª Delegacia de Polícia Civil Extremoz/RN', label: '23ª Delegacia de Polícia Civil Extremoz/RN' },
  { value: '24ª Delegacia de Polícia Civil São José de Mipibu/RN', label: '24ª Delegacia de Polícia Civil São José de Mipibu/RN' },
  { value: '25ª Delegacia de Polícia Civil Nísia Floresta/RN', label: '25ª Delegacia de Polícia Civil Nísia Floresta/RN' },
  { value: '26ª Delegacia de Polícia Civil Maxaranguape/RN', label: '26ª Delegacia de Polícia Civil Maxaranguape/RN' },
  { value: '27ª Delegacia de Polícia Civil Monte Alegre/RN', label: '27ª Delegacia de Polícia Civil Monte Alegre/RN' },
  { value: '28ª Delegacia de Polícia Civil Vera Cruz/RN', label: '28ª Delegacia de Polícia Civil Vera Cruz/RN' },
  { value: '29ª Delegacia de Polícia Civil Ielmo Marinho/RN', label: '29ª Delegacia de Polícia Civil Ielmo Marinho/RN' },
  { value: '30ª Delegacia de Polícia Civil Bom Jesus/RN', label: '30ª Delegacia de Polícia Civil Bom Jesus/RN' },
  { value: '31ª Delegacia de Polícia Civil Pureza/RN', label: '31ª Delegacia de Polícia Civil Pureza/RN' },
  { value: '32ª Delegacia de Polícia Civil Taipu/RN', label: '32ª Delegacia de Polícia Civil Taipu/RN' },
  { value: '33ª Delegacia de Polícia Civil São Paulo do Potengi/RN', label: '33ª Delegacia de Polícia Civil São Paulo do Potengi/RN' },
  { value: '34ª Delegacia de Polícia Civil São Tomé/RN', label: '34ª Delegacia de Polícia Civil São Tomé/RN' },
  { value: '36ª Delegacia de Polícia Civil Lajes/RN', label: '36ª Delegacia de Polícia Civil Lajes/RN' },
  { value: '37ª Delegacia de Polícia Civil Riachuelo/RN', label: '37ª Delegacia de Polícia Civil Riachuelo/RN' },
  { value: '38ª Delegacia de Polícia Civil Mossoró/RN', label: '38ª Delegacia de Polícia Civil Mossoró/RN' },
  { value: '39ª Delegacia de Polícia Civil Mossoró/RN', label: '39ª Delegacia de Polícia Civil Mossoró/RN' },
  { value: '40ª Delegacia de Polícia Civil Governador Dix-Sept Rosado/RN', label: '40ª Delegacia de Polícia Civil Governador Dix-Sept Rosado/RN' },
  { value: '41ª Delegacia de Polícia Civil Baraúna/RN', label: '41ª Delegacia de Polícia Civil Baraúna/RN' },
  { value: '42ª Delegacia de Polícia Civil Areia Branca/RN', label: '42ª Delegacia de Polícia Civil Areia Branca/RN' },
  { value: '43ª Delegacia de Polícia Civil Serra do Mel/RN', label: '43ª Delegacia de Polícia Civil Serra do Mel/RN' },
  { value: '44ª Delegacia de Polícia Civil Tibau/RN', label: '44ª Delegacia de Polícia Civil Tibau/RN' },
  { value: '45ª Delegacia de Polícia Civil Upanema/RN', label: '45ª Delegacia de Polícia Civil Upanema/RN' },
  { value: '46ª Delegacia de Polícia Civil Caicó/RN', label: '46ª Delegacia de Polícia Civil Caicó/RN' },
  { value: '47ª Delegacia de Polícia Civil Jardim de Piranhas/RN', label: '47ª Delegacia de Polícia Civil Jardim de Piranhas/RN' },
  { value: '48ª Delegacia de Polícia Civil Serra Negra do Norte/RN', label: '48ª Delegacia de Polícia Civil Serra Negra do Norte/RN' },
  { value: '49ª Delegacia de Polícia Civil Cruzeta/RN', label: '49ª Delegacia de Polícia Civil Cruzeta/RN' },
  { value: '50ª Delegacia de Polícia Civil Jardim do Seridó/RN', label: '50ª Delegacia de Polícia Civil Jardim do Seridó/RN' },
  { value: '51ª Delegacia de Polícia Civil Jucurutu/RN', label: '51ª Delegacia de Polícia Civil Jucurutu/RN' },
  { value: '52ª Delegacia de Polícia Civil São João do Sabugi/RN', label: '52ª Delegacia de Polícia Civil São João do Sabugi/RN' },
  { value: '53ª Delegacia de Polícia Civil Pau dos Ferros/RN', label: '53ª Delegacia de Polícia Civil Pau dos Ferros/RN' },
  { value: '54ª Delegacia de Polícia Civil São Francisco do Oeste/RN', label: '54ª Delegacia de Polícia Civil São Francisco do Oeste/RN' },
  { value: '55ª Delegacia de Polícia Civil São Miguel/RN', label: '55ª Delegacia de Polícia Civil São Miguel/RN' },
  { value: '56ª Delegacia de Polícia Civil Portalegre/RN', label: '56ª Delegacia de Polícia Civil Portalegre/RN' },
  { value: '57ª Delegacia de Polícia Civil Apodi/RN', label: '57ª Delegacia de Polícia Civil Apodi/RN' },
  { value: '58ª Delegacia de Polícia Civil Itaú/RN', label: '58ª Delegacia de Polícia Civil Itaú/RN' },
  { value: '59ª Delegacia de Polícia Civil Macau/RN', label: '59ª Delegacia de Polícia Civil Macau/RN' },
  { value: '60ª Delegacia de Polícia Civil Pendências/RN', label: '60ª Delegacia de Polícia Civil Pendências/RN' },
  { value: '61ª Delegacia de Polícia Civil Guamaré/RN', label: '61ª Delegacia de Polícia Civil Guamaré/RN' },
  { value: '62ª Delegacia de Polícia Civil Afonso Bezerra/RN', label: '62ª Delegacia de Polícia Civil Afonso Bezerra/RN' },
  { value: '63ª Delegacia de Polícia Civil Nova Cruz/RN', label: '63ª Delegacia de Polícia Civil Nova Cruz/RN' },
  { value: '64ª Delegacia de Polícia Civil Passa e Fica/RN', label: '64ª Delegacia de Polícia Civil Passa e Fica/RN' },
  { value: '65ª Delegacia de Polícia Civil Pedro Velho/RN', label: '65ª Delegacia de Polícia Civil Pedro Velho/RN' },
  { value: '66ª Delegacia de Polícia Civil Santo Antônio/RN', label: '66ª Delegacia de Polícia Civil Santo Antônio/RN' },
  { value: '67ª Delegacia de Polícia Civil Lagoa de Pedras/RN', label: '67ª Delegacia de Polícia Civil Lagoa de Pedras/RN' },
  { value: '68ª Delegacia de Polícia Civil Jundiá/RN', label: '68ª Delegacia de Polícia Civil Jundiá/RN' },
  { value: '69ª Delegacia de Polícia Civil São José do Campestre/RN', label: '69ª Delegacia de Polícia Civil São José do Campestre/RN' },
  { value: '70ª Delegacia de Polícia Civil Serra de São Bento/RN', label: '70ª Delegacia de Polícia Civil Serra de São Bento/RN' },
  { value: '71ª Delegacia de Polícia Civil Patu/RN', label: '71ª Delegacia de Polícia Civil Patu/RN' },
  { value: '72ª Delegacia de Polícia Civil Campo Grande/RN', label: '72ª Delegacia de Polícia Civil Campo Grande/RN' },
  { value: '73ª Delegacia de Polícia Civil Umarizal/RN', label: '73ª Delegacia de Polícia Civil Umarizal/RN' },
  { value: '74ª Delegacia de Polícia Civil Almino Afonso/RN', label: '74ª Delegacia de Polícia Civil Almino Afonso/RN' },
  { value: '75ª Delegacia de Polícia Civil Caraúbas/RN', label: '75ª Delegacia de Polícia Civil Caraúbas/RN' },
  { value: '76ª Delegacia de Polícia Civil Alexandria/RN', label: '76ª Delegacia de Polícia Civil Alexandria/RN' },
  { value: '77ª Delegacia de Polícia Civil Luís Gomes/RN', label: '77ª Delegacia de Polícia Civil Luís Gomes/RN' },
  { value: '78ª Delegacia de Polícia Civil Marcelino Vieira/RN', label: '78ª Delegacia de Polícia Civil Marcelino Vieira/RN' },
  { value: '79ª Delegacia de Polícia Civil Martins/RN', label: '79ª Delegacia de Polícia Civil Martins/RN' },
  { value: '80ª Delegacia de Polícia Civil Santa Cruz/RN', label: '80ª Delegacia de Polícia Civil Santa Cruz/RN' },
  { value: '81ª Delegacia de Polícia Civil Tangará/RN', label: '81ª Delegacia de Polícia Civil Tangará/RN' },
  { value: '82ª Delegacia de Polícia Civil Serra Caiada/RN', label: '82ª Delegacia de Polícia Civil Serra Caiada/RN' },
  { value: '83ª Delegacia de Polícia Civil Campo Redondo/RN', label: '83ª Delegacia de Polícia Civil Campo Redondo/RN' },
  { value: '84ª Delegacia de Polícia Civil Jaçanã/RN', label: '84ª Delegacia de Polícia Civil Jaçanã/RN' },
  { value: '85ª Delegacia de Polícia Civil João Câmara/RN', label: '85ª Delegacia de Polícia Civil João Câmara/RN' },
  { value: '86ª Delegacia de Polícia Civil Jandaíra/RN', label: '86ª Delegacia de Polícia Civil Jandaíra/RN' },
  { value: '88ª Delegacia de Polícia Civil Touros/RN', label: '88ª Delegacia de Polícia Civil Touros/RN' },
  { value: '89ª Delegacia de Polícia Civil São Miguel do Gostoso/RN', label: '89ª Delegacia de Polícia Civil São Miguel do Gostoso/RN' },
  { value: '90ª Delegacia de Polícia Civil São Bento do Norte/RN', label: '90ª Delegacia de Polícia Civil São Bento do Norte/RN' },
  { value: '91ª Delegacia de Polícia Civil Poço Branco/RN', label: '91ª Delegacia de Polícia Civil Poço Branco/RN' },
  { value: '92ª Delegacia de Polícia Civil Currais Novos/RN', label: '92ª Delegacia de Polícia Civil Currais Novos/RN' },
  { value: '93ª Delegacia de Polícia Civil Acari/RN', label: '93ª Delegacia de Polícia Civil Acari/RN' },
  { value: '94ª Delegacia de Polícia Civil Florânia/RN', label: '94ª Delegacia de Polícia Civil Florânia/RN' },
  { value: '95ª Delegacia de Polícia Civil Cerro Corá/RN', label: '95ª Delegacia de Polícia Civil Cerro Corá/RN' },
  { value: '96ª Delegacia de Polícia Civil Parelhas/RN', label: '96ª Delegacia de Polícia Civil Parelhas/RN' },
  { value: '97ª Delegacia de Polícia Civil Assu/RN', label: '97ª Delegacia de Polícia Civil Assu/RN' },
  { value: '98ª Delegacia de Polícia Civil Ipanguaçu/RN', label: '98ª Delegacia de Polícia Civil Ipanguaçu/RN' },
  { value: '99ª Delegacia de Polícia Civil Angicos/RN', label: '99ª Delegacia de Polícia Civil Angicos/RN' },
  { value: '100ª Delegacia de Polícia Civil Santana do Matos/RN', label: '100ª Delegacia de Polícia Civil Santana do Matos/RN' },
  { value: '101ª Delegacia de Polícia Civil Goianinha/RN', label: '101ª Delegacia de Polícia Civil Goianinha/RN' },
  { value: '102ª Delegacia de Polícia Civil Arês/RN', label: '102ª Delegacia de Polícia Civil Arês/RN' },
  { value: '103ª Delegacia de Polícia Civil Tibau do Sul/RN', label: '103ª Delegacia de Polícia Civil Tibau do Sul/RN' },
  { value: '104ª Delegacia de Polícia Civil Canguaretama/RN', label: '104ª Delegacia de Polícia Civil Canguaretama/RN' },
  { value: '105ª Delegacia de Polícia Civil Baía Formosa/RN', label: '105ª Delegacia de Polícia Civil Baía Formosa/RN' },
  { value: 'Delegacia Especializada de Atendimento à Mulher de Natal - Zonas Leste Oeste e Sul (DEAM/ZLOS)', label: 'DEAM/ZLOS - Natal' },
  { value: 'Delegacia Especializada de Atendimento à Mulher de Natal - Zona Norte (DEAM/ZN)', label: 'DEAM/ZN - Natal' },
  { value: 'Delegacia Especializada de Atendimento à Mulher de Parnamirim (DEAM/Parnamirim)', label: 'DEAM - Parnamirim' },
  { value: 'Delegacia Especializada de Atendimento à Mulher de Caicó (DEAM/Caicó)', label: 'DEAM - Caicó' },
  { value: 'Delegacia Especializada de Atendimento à Mulher de Mossoró (DEAM/Mossoró)', label: 'DEAM - Mossoró' },
  { value: 'Delegacia Especializada de Atendimento à Mulher de São Gonçalo do Amarante (DEAM/São Gonçalo do Amarante)', label: 'DEAM - São Gonçalo do Amarante' },
  { value: 'Delegacia Especializada de Atendimento à Mulher de Ceará-Mirim (DEAM/Ceará-Mirim)', label: 'DEAM - Ceará-Mirim' },
  { value: 'Delegacia Especializada de Atendimento à Mulher de Macaíba (DEAM/Macaíba)', label: 'DEAM - Macaíba' },
  { value: 'Delegacia Especializada de Atendimento à Mulher de Nova Cruz (DEAM/Nova Cruz)', label: 'DEAM - Nova Cruz' },
  { value: 'Delegacia Especializada de Atendimento à Mulher de Assu (DEAM/Assu)', label: 'DEAM - Assu' },
  { value: 'Delegacia Especializada de Atendimento à Mulher de Pau dos Ferros (DEAM/Pau dos Ferros)', label: 'DEAM - Pau dos Ferros' },
  { value: 'Delegacia Especializada de Atendimento à Mulher de Macau (DEAM/Macau)', label: 'DEAM - Macau' },
  { value: 'Delegacia Especializada na Proteção da Criança e do Adolescente de Natal (DPCA/Natal)', label: 'DPCA - Natal' },
  { value: 'Delegacia Especializada na Proteção da Criança e do Adolescente de Parnamirim (DPCA/Parnamirim)', label: 'DPCA - Parnamirim' },
  { value: 'Delegacia Especializada na Proteção da Criança e do Adolescente de Mossoró (DPCA/Mossoró)', label: 'DPCA - Mossoró' },
  { value: 'Delegacia Especializada de Proteção ao Idoso e à Pessoa com Deficiência de Natal (DEPID/Natal)', label: 'DEPID - Natal' },
  { value: 'Delegacia Especializada de Proteção ao Idoso e à Pessoa com Deficiência de Parnamirim (DEPID/Parnamirim)', label: 'DEPID - Parnamirim' },
  { value: '1ª Delegacia Regional (1ª DR) - São Paulo do Potengi/RN', label: '1ª DR - São Paulo do Potengi' },
  { value: '2ª Delegacia Regional (2ª DR) - Mossoró/RN', label: '2ª DR - Mossoró' },
  { value: '3ª Delegacia Regional (3ª DR) - Caicó/RN', label: '3ª DR - Caicó' },
  { value: '4ª Delegacia Regional (4ª DR) - Pau dos Ferros/RN', label: '4ª DR - Pau dos Ferros' },
  { value: '5ª Delegacia Regional (5ª DR) - Macau/RN', label: '5ª DR - Macau' },
  { value: '6ª Delegacia Regional (6ª DR) - Nova Cruz/RN', label: '6ª DR - Nova Cruz' },
  { value: '7ª Delegacia Regional (7ª DR) - Patu/RN', label: '7ª DR - Patu' },
  { value: '8ª Delegacia Regional (8ª DR) - Alexandria/RN', label: '8ª DR - Alexandria' },
  { value: '10ª Delegacia Regional (10ª DR) - João Câmara/RN', label: '10ª DR - João Câmara' },
  { value: '11ª Delegacia Regional (11ª DR) - Currais Novos/RN', label: '11ª DR - Currais Novos' },
  { value: '12ª Delegacia Regional (12ª DR) - Assú/RN', label: '12ª DR - Assú' },
  { value: '13ª Delegacia Regional (13ª DR) - Goianinha/RN', label: '13ª DR - Goianinha' },
  { value: '1ª Delegacia de Homicídios e de Proteção à Pessoa de Natal (1ª DH - Natal)', label: '1ª DH - Natal' },
  { value: '2ª Delegacia de Homicídios e de Proteção à Pessoa de Natal (2ª DH - Natal)', label: '2ª DH - Natal' },
  { value: '3ª Delegacia de Homicídios e de Proteção à Pessoa de Natal (3ª DH - Natal)', label: '3ª DH - Natal' },
  { value: '4ª Delegacia de Homicídios e de Proteção à Pessoa de Natal (4ª DH - Natal)', label: '4ª DH - Natal' },
  { value: '5ª Delegacia de Homicídios e de Proteção à Pessoa de Natal (5ª DH - Natal)', label: '5ª DH - Natal' },
  { value: '6ª Delegacia de Homicídios e de Proteção à Pessoa de Natal (6ª DH - Natal)', label: '6ª DH - Natal' },
  { value: '7ª Delegacia de Homicídios e de Proteção à Pessoa de Natal (7ª DH - Natal)', label: '7ª DH - Natal' },
  { value: '8ª Delegacia de Homicídios e de Proteção à Pessoa de Natal (8ª DH - Natal)', label: '8ª DH - Natal' },
  { value: '9ª Delegacia de Homicídios e de Proteção à Pessoa de Natal (9ª DH - Natal)', label: '9ª DH - Natal' },
  { value: '10ª Delegacia de Homicídios e de Proteção à Pessoa de Mossoró (10ª DH - Mossoró)', label: '10ª DH - Mossoró' },
  { value: '11ª Delegacia de Homicídios e de Proteção à Pessoa de Parnamirim (11ª DH - Parnamirim)', label: '11ª DH - Parnamirim' },
  { value: '12ª Delegacia de Homicídios e de Proteção à Pessoa de São Gonçalo do Amarante (12ª DH - São Gonçalo do Amarante)', label: '12ª DH - São Gonçalo do Amarante' },
  { value: '13ª Delegacia de Homicídios e de Proteção à Pessoa de Macaíba (13ª DH - Macaíba)', label: '13ª DH - Macaíba' },
  { value: '14ª Delegacia de Homicídios e de Proteção à Pessoa de Ceará-Mirim (14ª DH - Ceará-Mirim)', label: '14ª DH - Ceará-Mirim' },
  { value: '15ª Delegacia de Homicídios e de Proteção à Pessoa de Mossoró/RN (15ª DH - Mossoró)', label: '15ª DH - Mossoró' },
  { value: '16ª Delegacia de Homicídios e de Proteção à Pessoa de Mossoró/RN (16ª DH - Mossoró)', label: '16ª DH - Mossoró' },
  { value: '1ª Equipe da Delegacia de Plantão de Homicídios e de Proteção à Pessoa (DPH)', label: '1ª Equipe DPH' },
  { value: '2ª Equipe da Delegacia de Plantão de Homicídios e de Proteção à Pessoa (DPH)', label: '2ª Equipe DPH' },
  { value: '3ª Equipe da Delegacia de Plantão de Homicídios e de Proteção à Pessoa (DPH)', label: '3ª Equipe DPH' },
  { value: '4ª Equipe da Delegacia de Plantão de Homicídios e de Proteção à Pessoa (DPH)', label: '4ª Equipe DPH' },
  { value: '1ª Equipe da 1ª Delegacia de Plantão de Natal/RN', label: '1ª Equipe - 1ª DP Plantão Natal' },
  { value: '1ª Equipe da 2ª Delegacia de Plantão de Natal/RN', label: '1ª Equipe - 2ª DP Plantão Natal' },
  { value: '1ª Equipe da 3ª Delegacia de Plantão de Parnamirim/RN', label: '1ª Equipe - 3ª DP Plantão Parnamirim' },
  { value: '1ª Equipe da 4ª Delegacia de Plantão de São Gonçalo do Amarante/RN', label: '1ª Equipe - 4ª DP Plantão SGA' },
  { value: '1ª Equipe da Delegacia de Plantão de Caicó/RN', label: '1ª Equipe - DP Plantão Caicó' },
  { value: '1ª Equipe da Delegacia de Plantão de Mossoró/RN', label: '1ª Equipe - DP Plantão Mossoró' },
  { value: '2ª Equipe da 1ª Delegacia de Plantão de Natal/RN', label: '2ª Equipe - 1ª DP Plantão Natal' },
  { value: '2ª Equipe da 2ª Delegacia de Plantão de Natal/RN', label: '2ª Equipe - 2ª DP Plantão Natal' },
  { value: '2ª Equipe da 3ª Delegacia de Plantão de Parnamirim/RN', label: '2ª Equipe - 3ª DP Plantão Parnamirim' },
  { value: '2ª Equipe da 4ª Delegacia de Plantão de São Gonçalo do Amarante/RN', label: '2ª Equipe - 4ª DP Plantão SGA' },
  { value: '2ª Equipe da Delegacia de Plantão de Caicó/RN', label: '2ª Equipe - DP Plantão Caicó' },
  { value: '2ª Equipe da Delegacia de Plantão de Mossoró/RN', label: '2ª Equipe - DP Plantão Mossoró' },
  { value: '4ª Equipe da 1ª Delegacia de Plantão de Natal/RN', label: '4ª Equipe - 1ª DP Plantão Natal' },
  { value: '4ª Equipe da 2ª Delegacia de Plantão de Natal/RN', label: '4ª Equipe - 2ª DP Plantão Natal' },
  { value: '4ª Equipe da 3ª Delegacia de Plantão de Parnamirim/RN', label: '4ª Equipe - 3ª DP Plantão Parnamirim' },
  { value: '4ª Equipe da 4ª Delegacia de Plantão de São Gonçalo do Amarante/RN', label: '4ª Equipe - 4ª DP Plantão SGA' },
  { value: '4ª Equipe da Delegacia de Plantão de Caicó/RN', label: '4ª Equipe - DP Plantão Caicó' },
  { value: '4ª Equipe da Delegacia de Plantão de Mossoró/RN', label: '4ª Equipe - DP Plantão Mossoró' },
  { value: 'DEICOT - Delegacia Especializada de Investigação de Crimes Contra a Ordem Tributária', label: 'DEICOT' },
  { value: 'Delegacia Especializada de Atendimento ao Adolescente Infrator de Caicó (DEA/Caicó)', label: 'DEA - Caicó' },
  { value: 'Delegacia Especializada de Atendimento ao Adolescente Infrator de Mossoró (DEA/Mossoró)', label: 'DEA - Mossoró' },
  { value: 'Delegacia Especializada de Atendimento ao Adolescente Infrator de Natal (DEA/Natal)', label: 'DEA - Natal' },
  { value: 'Delegacia Especializada de Atendimento ao Adolescente Infrator de Parnamirim (DEA/Parnamirim)', label: 'DEA - Parnamirim' },
  { value: 'Delegacia Especializada de Capturas e Polícia Interestadual (DECAP/POLINTER)', label: 'DECAP/POLINTER' },
  { value: 'Delegacia Especializada de Combate a Crimes de Racismo Intolerância e Discriminação (DECRID)', label: 'DECRID' },
  { value: 'Delegacia Especializada de Defesa ao Meio Ambiente e Assistência ao Turista (DEMAATUR)', label: 'DEMAATUR' },
  { value: 'Delegacia Especializada de Defesa da Propriedade de Veículos e Cargas de Mossoró (DEPROV-Mossoró)', label: 'DEPROV - Mossoró' },
  { value: 'Delegacia Especializada de Defesa da Propriedade de Veículos e Cargas de Natal (DEPROV-Natal)', label: 'DEPROV - Natal' },
  { value: 'Delegacia Especializada de Defesa do Consumidor (DECON)', label: 'DECON' },
  { value: 'Delegacia Especializada de Defesa do Patrimônio Público e do Combate à Corrupção (DECCOR)', label: 'DECCOR' },
  { value: 'Delegacia Especializada de Falsificações e Defraudações de Mossoró (DEFD/Mossoró)', label: 'DEFD - Mossoró' },
  { value: 'Delegacia Especializada de Falsificações e Defraudações de Natal (DEFD/Natal)', label: 'DEFD - Natal' },
  { value: 'Delegacia Especializada de Furtos e Roubos de Caicó (DEFUR/Caicó)', label: 'DEFUR - Caicó' },
  { value: 'Delegacia Especializada de Furtos e Roubos de Mossoró (DEFUR/Mossoró)', label: 'DEFUR - Mossoró' },
  { value: 'Delegacia Especializada de Furtos e Roubos de Natal (DEFUR/Natal)', label: 'DEFUR - Natal' },
  { value: 'Delegacia Especializada de Narcóticos de Mossoró (DENARC/Mossoró)', label: 'DENARC - Mossoró' },
  { value: 'Delegacia Especializada de Narcóticos de Natal (DENARC/Natal)', label: 'DENARC - Natal' },
  { value: 'Delegacia Especializada de Repressão a Facções Criminosas (DEFAC)', label: 'DEFAC' },
  { value: 'Cartório da Delegacia Especializada de Repressão ao Crime Organizado (CART - DEICOR)', label: 'CART - DEICOR' },
  { value: 'Delegacia Especializada de Repressão a Roubos e Furtos contra Instituições Bancárias e Empresas de Transporte de Valores - DRFB', label: 'DRFB' },
  { value: 'Delegacia Especializada de Repressão ao Crime Organizado (DRACO)', label: 'DRACO' },
  { value: 'Delegacia Especializada em Crimes de Trânsito - DECT', label: 'DECT' },
  { value: 'Delegacia Especializada em Repressão a Crimes Cibernéticos (DERCC)', label: 'DERCC' },
  { value: 'Delegacia Especializada na Repressão a Lavagem de Dinheiro (DRLD)', label: 'DRLD' },
  { value: 'Promotoria de Justiça', label: 'Promotoria de Justiça' },
  { value: 'Ministério Público', label: 'Ministério Público' },
  { value: 'MPRN- Parnamirim', label: 'MPRN - Parnamirim' },
  { value: 'Tribunal de Justiça do Rio Grande do Norte (TJRN)', label: 'TJRN' },
] as const

export const getRequerenteLabel = (value: string): string => {
  const requerente = REQUERENTES.find(r => r.value === value)
  return requerente ? requerente.label : value
}
